apiVersion: v1
kind: ReplicationController
metadata:
  name: mem-alloc
spec:
  replicas: 1
  selector:
    name: mem-alloc
  template:
    metadata:
      labels:
        name: mem-alloc
    spec:
      containers:
      - name: centoscontainer
        image: registry.hundsun.com/hcs/mem_alloc:1.0.0
        command:
        - /mem_alloc
        - "-n"
        - "500"
        - "-t"
        - "1000"
        - "-d"
        - "3600"
